# Task 1: Basic prompt ############################
GET localhost:3000/task1?prompt="How are you today?"

###

# Task 2: System prompts ##########################

GET localhost:3000/task2?prompt="What are the latest fashion trends"
###
GET localhost:3000/task2?prompt="Recommend a car for me"

###

# Task 3: Chat Memory ##########################

GET localhost:3000/task3?prompt="Hi my name is Nick"
###
GET localhost:3000/task3?prompt="What's my name?"

###
# Task 4: Toool Calling ##########################
GET localhost:3000/task4?prompt="What cars do you have in stock?"

###
GET localhost:3000/task4?prompt="I want to buy the Porsche 911 and the Lexus IS."
